#ifndef _MENUCONSTANTS_H_
#define _MENUCONSTANTS_H_

//SPLASH
extern const char* SPLASH_SCREEN_NAME; 
extern const float SPLASH_PRESS_SPACE_Y_PERCENTAGE;

//MAINMENU
extern const char* MAINMENU_SCREEN_NAME;
extern const float MAINMENU_SELECT_ONE_PLAYER_Y_PERCENTAGE;
extern const float MAINMENU_SELECT_TWO_PLAYER_Y_PERCENTAGE;
extern const float MAINMENU_SELECT_CREDITS_Y_PERCENTAGE;
extern const float MAINMENU_SELECT_EXIT_Y_PERCENTAGE;

//CREDITS
extern const char* CREDITS_SCREEN_NAME;
extern const float CREDITS_SELECT_EXIT_Y_PERCENTAGE;
extern const float CREDITS_SELECT_GOBACK_Y_PERCENTAGE;

//GAME SETTINGS
extern const char* GAMESETTINGS_SCREEN_NAME;
extern const float GAMESETTINGS_SELECT_GOBACK_Y_PERCENTAGE;
extern const float GAMESETTINGS_SELECT_START_Y_PERCENTAGE;
extern const float GAMESETTINGS_SCORELIMIT_LOW_Y_PERCENTAGE;
extern const float GAMESETTINGS_SCORELIMIT_MID_Y_PERCENTAGE;
extern const float GAMESETTINGS_SCORELIMIT_NONE_Y_PERCENTAGE;
extern const float GAMESETTINGS_TIMELIMIT_LOW_Y_PERCENTAGE;
extern const float GAMESETTINGS_TIMELIMIT_MID_Y_PERCENTAGE;
extern const float GAMESETTINGS_TIMELIMIT_NONE_Y_PERCENTAGE;
extern const float GAMESETTINGS_DIFFICULTY_LOW_Y_PERCENTAGE;
extern const float GAMESETTINGS_DIFFICULTY_MID_Y_PERCENTAGE;
extern const float GAMESETTINGS_DIFFICULTY_HIGH_Y_PERCENTAGE;
extern const float GAMESETTINGS_CONTROLSELECT_MOUSE_Y_PERCENTAGE;
extern const float GAMESETTINGS_CONTROLSELECT_KEYS_Y_PERCENTAGE;

//TWO PLAYER GAME SETTINGS
extern const char* GAMESETTINGS_TWOS_SCREEN_NAME;
extern const float GAMESETTINGS_TWOS_SELECT_GOBACK_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_SELECT_START_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_SCORELIMIT_LOW_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_SCORELIMIT_MID_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_SCORELIMIT_NONE_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_TIMELIMIT_LOW_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_TIMELIMIT_MID_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_TIMELIMIT_NONE_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_P1_CONTROLSELECT_MOUSE_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_P1_CONTROLSELECT_KEYS_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_P2_CONTROLSELECT_MOUSE_Y_PERCENTAGE;
extern const float GAMESETTINGS_TWOS_P2_CONTROLSELECT_KEYS_Y_PERCENTAGE;

//PAUSE MENU
extern const char* PAUSE_SCREEN_NAME;
extern const float PAUSE_RESUME_Y_PERCENTAGE;
extern const float PAUSE_RESTART_Y_PERCENTAGE;
extern const float PAUSE_GOBACK_SETTINGS_Y_PERCENTAGE;
extern const float PAUSE_GOBACK_MAINMENU_Y_PERCENTAGE;

//GAMEOVER MENU (P1)
extern const char* GAMEOVER_SCREEN_NAME;
extern const float GAMEOVER_REPLAY_Y_PERCENTAGE;
extern const float GAMEOVER_RETURN_Y_PERCENTAGE;
extern const float GAMEOVER_EXIT_Y_PERCENTAGE;

//GAMEOVERMENU (P2)
extern const char* GAMEOVER_P2_SCREEN_NAME;

#endif