#include "MenuConstants.h"

//SPLASH
const char* SPLASH_SCREEN_NAME = "Splash_ScreenBG"; 
const float SPLASH_PRESS_SPACE_Y_PERCENTAGE = 0.78125f;

//MAIN MENU
const char* MAINMENU_SCREEN_NAME = "MainMenu_ScreenBG";
const float MAINMENU_SELECT_ONE_PLAYER_Y_PERCENTAGE = 0.42125f;
const float MAINMENU_SELECT_TWO_PLAYER_Y_PERCENTAGE = 0.54125f;
const float MAINMENU_SELECT_CREDITS_Y_PERCENTAGE = 0.66125;
const float MAINMENU_SELECT_EXIT_Y_PERCENTAGE = 0.78125;

//CREDITS
const char* CREDITS_SCREEN_NAME = "Credits_ScreenBG";
const float CREDITS_SELECT_GOBACK_Y_PERCENTAGE = 0.78125f;
const float CREDITS_SELECT_EXIT_Y_PERCENTAGE = 0.90125f;

//GAME SETTINGS
const char* GAMESETTINGS_SCREEN_NAME = "GameSettings_ScreenBG";

const float GAMESETTINGS_SELECT_START_Y_PERCENTAGE = 0.90125f;
const float GAMESETTINGS_SELECT_GOBACK_Y_PERCENTAGE = 0.90125f;

const float GAMESETTINGS_SCORELIMIT_LOW_Y_PERCENTAGE = 0.30125f;
const float GAMESETTINGS_SCORELIMIT_MID_Y_PERCENTAGE = 0.36125f;
const float GAMESETTINGS_SCORELIMIT_NONE_Y_PERCENTAGE = 0.42125f;

const float GAMESETTINGS_TIMELIMIT_LOW_Y_PERCENTAGE = 0.30125f;
const float GAMESETTINGS_TIMELIMIT_MID_Y_PERCENTAGE = 0.36125f;
const float GAMESETTINGS_TIMELIMIT_NONE_Y_PERCENTAGE = 0.42125f;

const float GAMESETTINGS_DIFFICULTY_LOW_Y_PERCENTAGE = 0.54125f;
const float GAMESETTINGS_DIFFICULTY_MID_Y_PERCENTAGE = 0.60125;
const float GAMESETTINGS_DIFFICULTY_HIGH_Y_PERCENTAGE = 0.66125f;

const float GAMESETTINGS_CONTROLSELECT_MOUSE_Y_PERCENTAGE = 0.54125f;
const float GAMESETTINGS_CONTROLSELECT_KEYS_Y_PERCENTAGE = 0.60125f;

//TWO PLAYER GAME SETTINGS
const char* GAMESETTINGS_TWOS_SCREEN_NAME = "GameSettingsTwos_ScreensBG";

const float GAMESETTINGS_TWOS_SELECT_GOBACK_Y_PERCENTAGE = 0.90125f;
const float GAMESETTINGS_TWOS_SELECT_START_Y_PERCENTAGE = 0.90125f;

const float GAMESETTINGS_TWOS_SCORELIMIT_LOW_Y_PERCENTAGE = 0.22125;
const float GAMESETTINGS_TWOS_SCORELIMIT_MID_Y_PERCENTAGE = 0.27125f;
const float GAMESETTINGS_TWOS_SCORELIMIT_NONE_Y_PERCENTAGE = 0.32125f;

const float GAMESETTINGS_TWOS_TIMELIMIT_LOW_Y_PERCENTAGE = 0.22125;
const float GAMESETTINGS_TWOS_TIMELIMIT_MID_Y_PERCENTAGE = 0.27125f;
const float GAMESETTINGS_TWOS_TIMELIMIT_NONE_Y_PERCENTAGE = 0.32125f;

const float GAMESETTINGS_TWOS_P1_CONTROLSELECT_MOUSE_Y_PERCENTAGE = 0.49125f;
const float GAMESETTINGS_TWOS_P1_CONTROLSELECT_KEYS_Y_PERCENTAGE = 0.54125f;

const float GAMESETTINGS_TWOS_P2_CONTROLSELECT_MOUSE_Y_PERCENTAGE = 0.49125f;
const float GAMESETTINGS_TWOS_P2_CONTROLSELECT_KEYS_Y_PERCENTAGE = 0.54125f;

//PAUSE MENU
const char* PAUSE_SCREEN_NAME = "Pause_ScreenBG";
const float PAUSE_RESUME_Y_PERCENTAGE = 0.42125f;
const float PAUSE_RESTART_Y_PERCENTAGE = 0.54125f;
const float PAUSE_GOBACK_SETTINGS_Y_PERCENTAGE = 0.66125;
const float PAUSE_GOBACK_MAINMENU_Y_PERCENTAGE = 0.78125;

//GAME OVER MENU (P1)
const char* GAMEOVER_SCREEN_NAME = "GameOver_P1Wins_ScreenBG";
const float GAMEOVER_REPLAY_Y_PERCENTAGE = 0.90125f;
const float GAMEOVER_RETURN_Y_PERCENTAGE = 0.90125f;
const float GAMEOVER_EXIT_Y_PERCENTAGE = 0.90125f;

//GAME OVER MENU (P2)
const char* GAMEOVER_P2_SCREEN_NAME = "GameOver_P2Wins_ScreenBG";